FROM registry.nersc.gov/library/nersc/mpi4py:3.1.3

# Install MPICH
WORKDIR /tmp
ARG MPICH_VERSION=4.2.2
ARG MPICH_PREFIX=mpich-$MPICH_VERSION

RUN wget https://www.mpich.org/static/downloads/$MPICH_VERSION/$MPICH_PREFIX.tar.gz
RUN tar xvzf $MPICH_PREFIX.tar.gz
RUN cd $MPICH_PREFIX && \
./configure && \
make -j 8 && \
make install && \
make clean && \
cd .. && \
rm -rf $MPICH_PREFIX

RUN /sbin/ldconfig

RUN pip install qiskit-aer-gpu